# .gitlab-ci.yml
image: node:16

cache:
  paths:
    - node_modules/

before_script:
  - cd Frontend
  - npm install

pages:
  script:
    - npm run dev
    - mv public ../public
  artifacts:
    paths:
      - public
  only:
    - main