# .gitlab-ci.yml

stages:
  - build

# Frontend build job
pages:
  image: node:latest
  stage: build
  
  cache:
    paths:
      - Frontend/node_modules/
  before_script:
    - cd Frontend
    - npm install
  script:
    - npm run build
    - mv public ../public
  artifacts:
    paths:
      - public
  only:
    - main

